"""
Seed the database with club data from Clubs.json
Run this script to populate the clubs table
"""
import sys
from datetime import datetime
from sqlalchemy import func
from sqlalchemy.orm import Session

from app.database import SessionLocal, engine, Base
from app.models.club import Club, ClubCategory


# Club data from Clubs.json in project root
# All logos are in frontend/public/images/clubs/{club_id}.jpg
CLUBS_DATA = [
    # ========== CO-CURRICULAR CLUBS (26) ==========
    {
        "name": "ACM (BMSCE ACM Student Chapter)",
        "slug": "acm",
        "category": ClubCategory.COCURRICULAR,
        "subcategory": "ai_ml",
        "tagline": "ACM student chapter — computing & AI",
        "description": "Established in 2021, the BMSCE ACM student chapter focuses on AI and ML concepts. It provides a platform for networking and collaboration among students and professionals.",
        "overview": "Established in 2021, the BMSCE ACM student chapter focuses on AI and ML concepts. It provides a platform for networking and collaboration among students and professionals, offering international perspectives in computer science.",
        "logo_url": "/images/clubs/acm.jpg",
        "instagram": "@bmsce_acm",
        "faculty_name": "Dr. Rajesh Kumar",
        "faculty_email": "rajesh.kumar@bmsce.ac.in",
        "faculty_phone": "9845123456",
        "member_count": 165,
        "view_count": 420,
        "is_active": True,
        "is_featured": True,
    },
    {
        "name": "Aquila Aerospace",
        "slug": "aquila",
        "category": ClubCategory.COCURRICULAR,
        "subcategory": "aerospace",
        "tagline": "Aeromodelling & aerospace",
        "description": "The student club of the department of aerospace engineering conducting technical and non-technical events for students and aerospace enthusiasts.",
        "overview": "Aquila Aerospace is the student club of the department of aerospace engineering. It conducts technical and non-technical events for students and aerospace enthusiasts, encouraging the spirit of elevate, lift, fly.",
        "logo_url": "/images/clubs/Aquila.jpg",
        "instagram": "@aquila_bmsce",
        "faculty_name": "Dr. Vishwanath Reddy",
        "faculty_email": "vishwanath.reddy@bmsce.ac.in",
        "member_count": 145,
        "view_count": 310,
        "is_active": True,
        "is_featured": False,
    },
    {
        "name": "Augment.AI",
        "slug": "augmentai",
        "category": ClubCategory.COCURRICULAR,
        "subcategory": "ai_ml",
        "tagline": "AI / ML student group",
        "description": "The artificial intelligence club initiated by the ISE department spreading awareness on AI and ML through events, workshops, and accelerator programs.",
        "overview": "The artificial intelligence club initiated by the ISE department. It spreads awareness on AI and ML through events, workshops, and accelerator programs, conducted quarterly.",
        "logo_url": "/images/clubs/AugmentAI.jpg",
        "instagram": "@augmentai_bmsce",
        "faculty_name": "Prof. Sneha Patil",
        "faculty_email": "sneha.patil@bmsce.ac.in",
        "member_count": 185,
        "view_count": 395,
        "is_active": True,
        "is_featured": True,
    },
    {
        "name": "AeroBMSCE",
        "slug": "aero",
        "category": ClubCategory.COCURRICULAR,
        "subcategory": "aerospace",
        "tagline": "Aeromodelling & drones",
        "description": "The Aeromodelling Club of BMSCE - a vibrant community for aircraft and drone enthusiasts participating in national and international competitions.",
        "overview": "AeroBMSCE, the Aeromodelling Club of BMSCE, is a vibrant community for aircraft and drone enthusiasts. The club participates in national and international aero-design competitions and offers a platform to learn, build and fly.",
        "logo_url": "/images/clubs/aero.JPG",
        "instagram": "@aerobmsce",
        "faculty_name": "Dr. Arun Sharma",
        "faculty_email": "arun.sharma@bmsce.ac.in",
        "member_count": 130,
        "view_count": 285,
        "is_active": True,
        "is_featured": False,
    },
    {
        "name": "Robotics Club",
        "slug": "robotics",
        "category": ClubCategory.COCURRICULAR,
        "subcategory": "robotics",
        "tagline": "Robotics innovation",
        "description": "Focused on learning and innovation in robotics with hands-on experience in designing and programming robotic systems.",
        "overview": "Focused on learning and innovation in robotics. Members design and program robotic systems, gaining hands-on experience while exploring creativity and engineering problem-solving.",
        "logo_url": "/images/clubs/robotics.JPG",
        "instagram": "@robotics_bmsce",
        "faculty_name": "Dr. Vikram Singh",
        "faculty_email": "vikram.singh@bmsce.ac.in",
        "member_count": 155,
        "view_count": 340,
        "is_active": True,
        "is_featured": False,
    },
    {
        "name": "Rocketry",
        "slug": "rocketry",
        "category": ClubCategory.COCURRICULAR,
        "subcategory": "aerospace",
        "tagline": "Model rocketry",
        "description": "The model rocket club of BMSCE where students collaborate to design and work with rockets through project-based learning.",
        "overview": "Rocketry is the model rocket club of BMSCE where students collaborate to design and work with rockets. The club provides a launchpad for project-based learning and rocket challenges, encouraging teamwork and exploration in rocket science.",
        "logo_url": "/images/clubs/Rocketry.JPG",
        "instagram": "@rocketry_bmsce",
        "faculty_name": "Prof. Kavita Nair",
        "faculty_email": "kavita.nair@bmsce.ac.in",
        "member_count": 95,
        "view_count": 215,
        "is_active": True,
        "is_featured": False,
    },
    {
        "name": "Bullz Racing (SAE)",
        "slug": "bullz",
        "category": ClubCategory.COCURRICULAR,
        "subcategory": "technical",
        "tagline": "Formula student / motorsport",
        "description": "The formula student team of BMSCE designing and building formula-style race cars for national-level motorsport competitions.",
        "overview": "The formula student team of BMSCE, designing and building formula-style race cars and competing in national-level motorsport competitions.",
        "logo_url": "/images/clubs/bullz.jpg",
        "instagram": "@bullzracing_bmsce",
        "faculty_name": "Dr. Manoj Kumar",
        "faculty_email": "manoj.kumar@bmsce.ac.in",
        "member_count": 85,
        "view_count": 195,
        "is_active": True,
        "is_featured": False,
    },
    {
        "name": "TeamCodeLocked",
        "slug": "teamcodelocked",
        "category": ClubCategory.COCURRICULAR,
        "subcategory": "coding",
        "tagline": "Coding & competitive programming",
        "description": "The premier coding club of BMSCE open to students from all branches focusing on coding proficiency through competitions and workshops.",
        "overview": "TeamCodeLocked is the premier coding club of BMSCE, open to students from all branches; it focuses on coding proficiency via competitions, collaboration and workshops.",
        "logo_url": "/images/clubs/teamcodelocked.JPG",
        "instagram": "@teamcodelocked",
        "faculty_name": "Prof. Deepa Rao",
        "faculty_email": "deepa.rao@bmsce.ac.in",
        "member_count": 210,
        "view_count": 485,
        "is_active": True,
        "is_featured": True,
    },
    {
        "name": "DSYNC (Data Science)",
        "slug": "dsync",
        "category": ClubCategory.COCURRICULAR,
        "subcategory": "ai_ml",
        "tagline": "Data science & analytics",
        "description": "The first data science club at BMSCE building strong coding, analytical, and collaborative skills among data science enthusiasts.",
        "overview": "The first data science club at BMSCE aimed at building strong coding, analytical, and collaborative skills among data science enthusiasts.",
        "logo_url": "/images/clubs/Dsync.jpg",
        "instagram": "@dsync_bmsce",
        "faculty_name": "Dr. Priya Mehta",
        "faculty_email": "priya.mehta@bmsce.ac.in",
        "member_count": 175,
        "view_count": 380,
        "is_active": True,
        "is_featured": True,
    },
    {
        "name": "Varaince (AI & Data Science)",
        "slug": "varaince",
        "category": ClubCategory.COCURRICULAR,
        "subcategory": "ai_ml",
        "tagline": "AI & data science community",
        "description": "A community centered around artificial intelligence and data science running seminars, hands-on sessions, hackathons and mentorship.",
        "overview": "A community centered around artificial intelligence and data science that runs seminars, hands-on sessions, hackathons and mentorship for aspiring AI/DS professionals.",
        "logo_url": "/images/clubs/varaince.JPG",
        "instagram": "@varaince_bmsce",
        "faculty_name": "Prof. Amit Deshmukh",
        "faculty_email": "amit.deshmukh@bmsce.ac.in",
        "member_count": 190,
        "view_count": 425,
        "is_active": True,
        "is_featured": True,
    },
    {
        "name": "CORTECHS",
        "slug": "corrtechs",
        "category": ClubCategory.COCURRICULAR,
        "subcategory": "innovation",
        "tagline": "MedTech & healthcare innovation",
        "description": "Uniting students passionate about MedTech and healthcare technology to reimagine healthcare solutions.",
        "overview": "CORTECHS (formerly AME) unites students passionate about MedTech and healthcare technology to reimagine healthcare solutions, empowering innovation across electronics, AI and healthcare.",
        "logo_url": "/images/clubs/corrtechs.jpg",
        "instagram": "@cortechs_bmsce",
        "faculty_name": "Dr. Sunita Iyer",
        "faculty_email": "sunita.iyer@bmsce.ac.in",
        "member_count": 125,
        "view_count": 275,
        "is_active": True,
        "is_featured": False,
    },
    {
        "name": "CIIE (Centre for Innovation, Incubation & Entrepreneurship)",
        "slug": "ciie",
        "category": ClubCategory.COCURRICULAR,
        "subcategory": "innovation",
        "tagline": "Entrepreneurship & startups",
        "description": "Supporting student entrepreneurship, incubation and startup workshops and activities.",
        "overview": "CIIE supports student entrepreneurship, incubation & startup workshops and activities.",
        "logo_url": "/images/clubs/ciie.jpg",
        "instagram": "@ciie_bmsce",
        "faculty_name": "Prof. Ramesh Kulkarni",
        "faculty_email": "ramesh.kulkarni@bmsce.ac.in",
        "member_count": 140,
        "view_count": 305,
        "is_active": True,
        "is_featured": False,
    },
    {
        "name": "IIC BMSCE (Startup Cell)",
        "slug": "iic",
        "category": ClubCategory.COCURRICULAR,
        "subcategory": "innovation",
        "tagline": "Startup support & incubation",
        "description": "Institute Innovation Council / Startup Cell facilitating new ventures, events, and incubation activities.",
        "overview": "Institute Innovation Council / Startup Cell facilitating new ventures, events, and incubation activities.",
        "logo_url": "/images/clubs/iic.jpg",
        "instagram": "@iic_bmsce",
        "faculty_name": "Dr. Lakshmi Narayan",
        "faculty_email": "lakshmi.narayan@bmsce.ac.in",
        "member_count": 160,
        "view_count": 350,
        "is_active": True,
        "is_featured": False,
    },
    {
        "name": "EDC - Entrepreneur Development Cell",
        "slug": "edc",
        "category": ClubCategory.COCURRICULAR,
        "subcategory": "innovation",
        "tagline": "Entrepreneur development",
        "description": "Organizing entrepreneurship development programs and workshops to build entrepreneurial skills.",
        "overview": "EDC organises entrepreneurship development programs and workshops to build entrepreneurial skills.",
        "logo_url": "/images/clubs/edc.jpg",
        "instagram": "@edc_bmsce",
        "faculty_name": "Prof. Anjali Verma",
        "faculty_email": "anjali.verma@bmsce.ac.in",
        "member_count": 135,
        "view_count": 295,
        "is_active": True,
        "is_featured": False,
    },
    {
        "name": "Business Insights",
        "slug": "business-insights",
        "category": ClubCategory.COCURRICULAR,
        "subcategory": "technical",
        "tagline": "Business & finance club",
        "description": "The business club of BMSCE inspiring entrepreneurship and managerial thinking through workshops, networking, and finance sessions.",
        "overview": "The business club of BMSCE aimed at inspiring entrepreneurship and managerial thinking through workshops, networking, and finance sessions.",
        "logo_url": "/images/clubs/business-insights.JPG",
        "instagram": "@businessinsights_bmsce",
        "faculty_name": "Prof. Suresh Menon",
        "faculty_email": "suresh.menon@bmsce.ac.in",
        "member_count": 115,
        "view_count": 255,
        "is_active": True,
        "is_featured": False,
    },
    {
        "name": "Pentagram (Mathematics Society)",
        "slug": "pentagram",
        "category": ClubCategory.COCURRICULAR,
        "subcategory": "technical",
        "tagline": "Mathematics & problem solving",
        "description": "The Mathematical Society promoting curiosity in mathematics through competitions, discussions and collaborative learning.",
        "overview": "The Mathematical Society promoting curiosity in mathematics via competitions, discussions and collaborative learning.",
        "logo_url": "/images/clubs/Pentagram.JPG",
        "instagram": "@pentagram_bmsce",
        "faculty_name": "Dr. Srinivas Rao",
        "faculty_email": "srinivas.rao@bmsce.ac.in",
        "member_count": 105,
        "view_count": 230,
        "is_active": True,
        "is_featured": False,
    },
    {
        "name": "Mechanical Engineering Association (MEA)",
        "slug": "mea",
        "category": ClubCategory.COCURRICULAR,
        "subcategory": "technical",
        "tagline": "Mechanical engineering community",
        "description": "Club for mechanical engineering students conducting technical seminars, workshops and the departmental fest 'Dynamech'.",
        "overview": "Club for mechanical engineering students conducting technical seminars, workshops and the departmental fest 'Dynamech' with an industry-orientated focus.",
        "logo_url": "/images/clubs/mea.JPG",
        "instagram": "@mea_bmsce",
        "faculty_name": "Dr. Harish Gowda",
        "faculty_email": "harish.gowda@bmsce.ac.in",
        "member_count": 195,
        "view_count": 425,
        "is_active": True,
        "is_featured": False,
    },
    {
        "name": "ELSOC (Electronics Society)",
        "slug": "elsoc",
        "category": ClubCategory.COCURRICULAR,
        "subcategory": "technical",
        "tagline": "Electronics & VLSI community",
        "description": "Running electronics workshops, project support and student activities focused on VLSI, robotics and related fields.",
        "overview": "ELSOC runs electronics workshops, project support and student activities focused on VLSI, robotics and related fields.",
        "logo_url": "/images/clubs/ElSoc.jpg",
        "instagram": "@elsoc_bmsce",
        "faculty_name": "Dr. Anita Desai",
        "faculty_email": "anita.desai@bmsce.ac.in",
        "member_count": 170,
        "view_count": 375,
        "is_active": True,
        "is_featured": False,
    },
    {
        "name": "BMSCE IEEE Computer Society",
        "slug": "ieee-cs",
        "category": ClubCategory.COCURRICULAR,
        "subcategory": "technical",
        "tagline": "IEEE Computer Society",
        "description": "Supporting development in computer science research and technology through workshops, seminars, hackathons, and networking.",
        "overview": "Supports development in computer science research and technology through workshops, seminars, hackathons, and networking.",
        "logo_url": "/images/clubs/ieee-cs.jpg",
        "instagram": "@ieee_cs_bmsce",
        "faculty_name": "Dr. Madhav Rao",
        "faculty_email": "madhav.rao@bmsce.ac.in",
        "member_count": 205,
        "view_count": 465,
        "is_active": True,
        "is_featured": True,
    },
    {
        "name": "BMSCE IEEE Student Branch",
        "slug": "ieee-sb",
        "category": ClubCategory.COCURRICULAR,
        "subcategory": "technical",
        "tagline": "IEEE student branch",
        "description": "Founded in 2009, organizing technical activities to keep students updated with evolving technology.",
        "overview": "Founded in 2009, the student branch organises technical activities to keep students updated with evolving technology.",
        "logo_url": "/images/clubs/ieee-sb.jpg",
        "instagram": "@ieee_bmsce",
        "faculty_name": "Prof. Kiran Kumar",
        "faculty_email": "kiran.kumar@bmsce.ac.in",
        "member_count": 220,
        "view_count": 510,
        "is_active": True,
        "is_featured": True,
    },
    {
        "name": "BMSCE IEEE WIE",
        "slug": "ieee-wie",
        "category": ClubCategory.COCURRICULAR,
        "subcategory": "technical",
        "tagline": "Women in Engineering",
        "description": "Women in Engineering chapter promoting equality in STEM and professional skill development among women students.",
        "overview": "Women in Engineering chapter promoting equality in STEM and professional skill development among women students.",
        "logo_url": "/images/clubs/ieee-wie.jpg",
        "instagram": "@ieee_wie_bmsce",
        "faculty_name": "Dr. Pooja Shetty",
        "faculty_email": "pooja.shetty@bmsce.ac.in",
        "member_count": 145,
        "view_count": 320,
        "is_active": True,
        "is_featured": False,
    },
    {
        "name": "IEEE PES & Sensors Council",
        "slug": "ieee-pes",
        "category": ClubCategory.COCURRICULAR,
        "subcategory": "technical",
        "tagline": "Power & sensors community",
        "description": "Focusing on power systems, sustainability and energy technologies through workshops and training.",
        "overview": "Focuses on power systems, sustainability and energy technologies through workshops and training.",
        "logo_url": "/images/clubs/ieee-pes.jpg",
        "instagram": "@ieee_pes_bmsce",
        "faculty_name": "Dr. Naveen Gowda",
        "faculty_email": "naveen.gowda@bmsce.ac.in",
        "member_count": 125,
        "view_count": 280,
        "is_active": True,
        "is_featured": False,
    },
    {
        "name": "IEEE Signal Processing Society",
        "slug": "ieee-sps",
        "category": ClubCategory.COCURRICULAR,
        "subcategory": "technical",
        "tagline": "Signal processing research",
        "description": "Dedicated to signal processing theory and applications through conferences, workshops and knowledge sharing.",
        "overview": "Dedicated to signal processing theory and applications; organises conferences, workshops and knowledge sharing.",
        "logo_url": "/images/clubs/ieee-sps.JPG",
        "instagram": "@ieee_sps_bmsce",
        "faculty_name": "Prof. Meena Krishnan",
        "faculty_email": "meena.krishnan@bmsce.ac.in",
        "member_count": 110,
        "view_count": 245,
        "is_active": True,
        "is_featured": False,
    },
    {
        "name": "GDSC (Google Developer Student Club)",
        "slug": "gdscl",
        "category": ClubCategory.COCURRICULAR,
        "subcategory": "coding",
        "tagline": "Developer community",
        "description": "A student-driven group promoting hands-on projects, workshops and innovation-focused activities.",
        "overview": "A student-driven group promoting hands-on projects, workshops and innovation-focused activities.",
        "logo_url": "/images/clubs/gdscl.jpg",
        "instagram": "@gdsc_bmsce",
        "faculty_name": "Prof. Arjun Nair",
        "faculty_email": "arjun.nair@bmsce.ac.in",
        "member_count": 200,
        "view_count": 475,
        "is_active": True,
        "is_featured": True,
    },
    {
        "name": "Synapse (Biotech)",
        "slug": "synapse",
        "category": ClubCategory.COCURRICULAR,
        "subcategory": "research",
        "tagline": "Biotechnology students' association",
        "description": "The biotechnology students' association supporting academic growth through workshops, quizzes and hands-on training.",
        "overview": "The biotechnology students' association supporting academic growth through workshops, quizzes and hands-on training for young scientists.",
        "logo_url": "/images/clubs/synapse.JPG",
        "instagram": "@synapse_bmsce",
        "faculty_name": "Dr. Nandini Rao",
        "faculty_email": "nandini.rao@bmsce.ac.in",
        "member_count": 120,
        "view_count": 270,
        "is_active": True,
        "is_featured": False,
    },
    {
        "name": "Upagraha",
        "slug": "upagraha",
        "category": ClubCategory.COCURRICULAR,
        "subcategory": "aerospace",
        "tagline": "Student satellite initiative",
        "description": "A student-driven satellite development initiative designing and launching a nanosatellite into low earth orbit.",
        "overview": "A student-driven satellite development initiative (with industry partners) involved in designing and launching a nanosatellite into low earth orbit.",
        "logo_url": "/images/clubs/upagraha.JPG",
        "instagram": "@upagraha_bmsce",
        "faculty_name": "Dr. Vivek Sharma",
        "faculty_email": "vivek.sharma@bmsce.ac.in",
        "member_count": 75,
        "view_count": 185,
        "is_active": True,
        "is_featured": False,
    },

    # ========== DEPARTMENT CLUBS (10) ==========
    {
        "name": "<CodeIO/>",
        "slug": "codeio",
        "category": ClubCategory.DEPARTMENT,
        "subcategory": "cse",
        "tagline": "CSE technical community",
        "description": "A technical community in the CSE department focused on technical upskilling through hackathons, workshops, and development projects.",
        "overview": "A technical community in the CSE department focused on technical upskilling through hackathons, workshops, coding sessions, R&D activities and development projects such as web applications.",
        "logo_url": "/images/clubs/CodeIO.jpg",
        "instagram": "@codeio_bmsce",
        "faculty_name": "Dr. Sunil Kumar",
        "faculty_email": "sunil.kumar@bmsce.ac.in",
        "member_count": 240,
        "view_count": 555,
        "is_active": True,
        "is_featured": True,
    },
    {
        "name": "PROTOCOL",
        "slug": "protocol",
        "category": ClubCategory.DEPARTMENT,
        "subcategory": "cse",
        "tagline": "CSE departmental club",
        "description": "The CSE departmental club focused on technical skill development through workshops, talks, competitions, and Protocol Day.",
        "overview": "The CSE departmental club focused on technical skill development. It conducts workshops, talks, competitions, and Protocol Day to enhance problem-solving and conceptual understanding in computer science.",
        "logo_url": "/images/clubs/protocol.JPG",
        "instagram": "@protocol_bmsce",
        "faculty_name": "Prof. Ravi Shankar",
        "faculty_email": "ravi.shankar@bmsce.ac.in",
        "member_count": 235,
        "view_count": 530,
        "is_active": True,
        "is_featured": True,
    },
    {
        "name": "ISE STUDENT CLUB",
        "slug": "iseclub",
        "category": ClubCategory.DEPARTMENT,
        "subcategory": "ise",
        "tagline": "ISE student community",
        "description": "A collaborative student-run club promoting holistic development, peer learning and community-building activities in the ISE department.",
        "overview": "A collaborative student-run club promoting holistic development, peer learning and community-building activities in the ISE department.",
        "logo_url": "/images/clubs/iseclub.jpg",
        "instagram": "@ise_club_bmsce",
        "faculty_name": "Prof. Geeta Patel",
        "faculty_email": "geeta.patel@bmsce.ac.in",
        "member_count": 215,
        "view_count": 485,
        "is_active": True,
        "is_featured": True,
    },
    {
        "name": "EEE Association",
        "slug": "eeea",
        "category": ClubCategory.DEPARTMENT,
        "subcategory": "eee",
        "tagline": "Electrical & Electronics community",
        "description": "A community for electrical and electronics engineering students organizing workshops, seminars and industrial visits.",
        "overview": "A community for students interested in electrical and electronics engineering, organizing workshops, seminars and industrial visits to strengthen learning and innovation.",
        "logo_url": "/images/clubs/eeea.jpg",
        "instagram": "@eee_bmsce",
        "faculty_name": "Dr. Prakash Reddy",
        "faculty_email": "prakash.reddy@bmsce.ac.in",
        "member_count": 190,
        "view_count": 430,
        "is_active": True,
        "is_featured": False,
    },
    {
        "name": "Gradient",
        "slug": "gradient",
        "category": ClubCategory.DEPARTMENT,
        "subcategory": "other",
        "tagline": "AI/ML / AIML club",
        "description": "The AIML club of BMSCE providing real-world project exposure and skill-building in artificial intelligence.",
        "overview": "The AIML club of BMSCE providing real-world project exposure and skill-building in artificial intelligence and application-based learning.",
        "logo_url": "/images/clubs/Gradient.jpg",
        "instagram": "@gradient_bmsce",
        "faculty_name": "Dr. Swathi Lakshmi",
        "faculty_email": "swathi.lakshmi@bmsce.ac.in",
        "member_count": 180,
        "view_count": 410,
        "is_active": True,
        "is_featured": False,
    },
    # Note: The following clubs appear in both categories in the source JSON
    # Adding them with dept-specific slugs to avoid conflicts
    {
        "name": "Aquila (Aerospace Dept)",
        "slug": "aquila-dept",
        "category": ClubCategory.DEPARTMENT,
        "subcategory": "aerospace_dept",
        "tagline": "Aeromodelling & aerospace",
        "description": "The departmental aerospace engineering club conducting technical and non-technical events.",
        "overview": "Aquila Aerospace is the student club of the department of aerospace engineering. It conducts technical and non-technical events for students and aerospace enthusiasts, encouraging the spirit of elevate, lift, fly.",
        "logo_url": "/images/clubs/Aquila.jpg",
        "instagram": "@aquila_ae_dept",
        "faculty_name": "Dr. Vishwanath Reddy",
        "faculty_email": "vishwanath.reddy@bmsce.ac.in",
        "member_count": 155,
        "view_count": 340,
        "is_active": True,
        "is_featured": False,
    },
    {
        "name": "DSync (Data Science Dept)",
        "slug": "dsync-dept",
        "category": ClubCategory.DEPARTMENT,
        "subcategory": "other",
        "tagline": "Data science & analytics",
        "description": "The departmental data science club building analytical and collaborative skills.",
        "overview": "The first data science club at BMSCE aimed at building strong coding, analytical and collaborative skills among data science enthusiasts.",
        "logo_url": "/images/clubs/Dsync.jpg",
        "instagram": "@dsync_dept",
        "faculty_name": "Dr. Priya Mehta",
        "faculty_email": "priya.mehta@bmsce.ac.in",
        "member_count": 165,
        "view_count": 365,
        "is_active": True,
        "is_featured": False,
    },
    {
        "name": "ELSOC (ECE Dept)",
        "slug": "elsoc-dept",
        "category": ClubCategory.DEPARTMENT,
        "subcategory": "other",
        "tagline": "Electronics & VLSI community",
        "description": "The ECE department electronics society conducting workshops and events in VLSI and robotics.",
        "overview": "The student community of the ECE department conducting workshops and events to inspire innovation in VLSI, robotics, AI and other advanced technology domains.",
        "logo_url": "/images/clubs/ElSoc.jpg",
        "instagram": "@elsoc_ece_dept",
        "faculty_name": "Dr. Anita Desai",
        "faculty_email": "anita.desai@bmsce.ac.in",
        "member_count": 175,
        "view_count": 385,
        "is_active": True,
        "is_featured": False,
    },
    {
        "name": "Synapse (Biotech Dept)",
        "slug": "synapse-dept",
        "category": ClubCategory.DEPARTMENT,
        "subcategory": "other",
        "tagline": "Biotech students' association",
        "description": "The departmental biotechnology association supporting academic and career growth.",
        "overview": "The first biotechnology students' association supporting academic and career growth through workshops, quizzes, themed events, hands-on training and community building among young scientists and innovators.",
        "logo_url": "/images/clubs/synapse.JPG",
        "instagram": "@synapse_biotech_dept",
        "faculty_name": "Dr. Nandini Rao",
        "faculty_email": "nandini.rao@bmsce.ac.in",
        "member_count": 145,
        "view_count": 315,
        "is_active": True,
        "is_featured": False,
    },
    {
        "name": "VarAInce (AI/DS Dept)",
        "slug": "varaince-dept",
        "category": ClubCategory.DEPARTMENT,
        "subcategory": "other",
        "tagline": "AI & Data Science community",
        "description": "The departmental AI and data science community running seminars, hackathons and mentorship programs.",
        "overview": "A community centered around artificial intelligence and data science that runs seminars, hands-on sessions, hackathons and mentorship for aspiring AI/DS professionals.",
        "logo_url": "/images/clubs/varaince.JPG",
        "instagram": "@varaince_dept",
        "faculty_name": "Prof. Amit Deshmukh",
        "faculty_email": "amit.deshmukh@bmsce.ac.in",
        "member_count": 170,
        "view_count": 380,
        "is_active": True,
        "is_featured": False,
    },

    # ========== EXTRA-CURRICULAR - SOCIAL (5) ==========
    {
        "name": "National Service Scheme (NSS)",
        "slug": "nss",
        "category": ClubCategory.EXTRACURRICULAR,
        "subcategory": "social",
        "tagline": "Social outreach & service",
        "description": "The NSS unit encouraging social responsibility and community service through welfare initiatives and volunteering.",
        "overview": "The NSS unit encourages social responsibility and community service. Members engage in welfare initiatives and volunteering activities, developing empathy, leadership, and teamwork.",
        "logo_url": "/images/clubs/nss.JPG",
        "instagram": "@nss_bmsce",
        "faculty_name": "Prof. Ramya Krishnan",
        "faculty_email": "ramya.krishnan@bmsce.ac.in",
        "member_count": 185,
        "view_count": 405,
        "is_active": True,
        "is_featured": False,
    },
    {
        "name": "Rotaract Club of BMSCE",
        "slug": "rotaract",
        "category": ClubCategory.EXTRACURRICULAR,
        "subcategory": "social",
        "tagline": "Leadership & Community Service",
        "description": "The Rotaract club focused on community service, professional development and international service building leadership.",
        "overview": "The Rotaract club of BMSCE is focused on community service, professional development and international service; members engage in impactful activities that build leadership and contribute to positive change.",
        "logo_url": "/images/clubs/rotaract.JPG",
        "instagram": "@rotaract_bmsce",
        "faculty_name": "Prof. Lakshmi Iyer",
        "faculty_email": "lakshmi.iyer@bmsce.ac.in",
        "member_count": 165,
        "view_count": 360,
        "is_active": True,
        "is_featured": False,
    },
    {
        "name": "Leo Satva",
        "slug": "leosatva",
        "category": ClubCategory.EXTRACURRICULAR,
        "subcategory": "social",
        "tagline": "Leadership & service (Lions-affiliated)",
        "description": "Affiliated with Lions Clubs International, promoting leadership, service and community engagement through volunteer projects.",
        "overview": "Affiliated with Lions Clubs International, promoting leadership, service and community engagement through volunteer projects.",
        "logo_url": "/images/clubs/leosatva.JPG",
        "instagram": "@leosatva_bmsce",
        "faculty_name": "Prof. Ashok Kumar",
        "faculty_email": "ashok.kumar@bmsce.ac.in",
        "member_count": 95,
        "view_count": 215,
        "is_active": True,
        "is_featured": False,
    },
    {
        "name": "Mountaineering Club",
        "slug": "mountaineering",
        "category": ClubCategory.EXTRACURRICULAR,
        "subcategory": "sports",
        "tagline": "Outdoors & trekking",
        "description": "Promoting wall climbing, slacklining, bouldering, rappelling and hiking through climbing trips and sustainable treks.",
        "overview": "The Mountaineering Club promotes wall climbing, slacklining, bouldering, rappelling and hiking, organizing climbing trips and sustainable treks for beginners and experienced climbers.",
        "logo_url": "/images/clubs/mountaineering.JPG",
        "instagram": "@mountaineering_bmsce",
        "faculty_name": "Prof. Aditya Rao",
        "faculty_email": "aditya.rao@bmsce.ac.in",
        "member_count": 110,
        "view_count": 245,
        "is_active": True,
        "is_featured": False,
    },
    {
        "name": "Respawn (Gaming Club)",
        "slug": "respawn",
        "category": ClubCategory.EXTRACURRICULAR,
        "subcategory": "sports",
        "tagline": "Competitive & social gaming",
        "description": "The official gaming club hosting tournaments for popular competitive titles and providing a space for gaming.",
        "overview": "The official gaming club hosting tournaments for popular competitive titles and providing a space for social and competitive gaming.",
        "logo_url": "/images/clubs/Respawn.JPG",
        "instagram": "@respawn_bmsce",
        "faculty_name": "Prof. Karthik Nair",
        "faculty_email": "karthik.nair@bmsce.ac.in",
        "member_count": 135,
        "view_count": 295,
        "is_active": True,
        "is_featured": False,
    },

    # ========== EXTRA-CURRICULAR - CULTURAL (12) ==========
    {
        "name": "Inksanity – Literary & Debate Society",
        "slug": "inksanity",
        "category": ClubCategory.EXTRACURRICULAR,
        "subcategory": "literature",
        "tagline": "Literary & Debate",
        "description": "The literary and debate society providing a platform for writing, debating, discussion, and creative expression.",
        "overview": "The literary and debate society providing a platform for writing, debating, discussion, and creative expression.",
        "logo_url": "/images/clubs/Inksanity.jpg",
        "instagram": "@inksanity_bmsce",
        "faculty_name": "Prof. Meera Nambiar",
        "faculty_email": "meera.nambiar@bmsce.ac.in",
        "member_count": 125,
        "view_count": 280,
        "is_active": True,
        "is_featured": False,
    },
    {
        "name": "Ninaad (Eastern Music)",
        "slug": "ninaad",
        "category": ClubCategory.EXTRACURRICULAR,
        "subcategory": "music",
        "tagline": "Music & performance",
        "description": "The Eastern music club promoting Carnatic, Hindustani, light, folk and film music.",
        "overview": "The Eastern music club promoting Carnatic, Hindustani, light, folk and film music; a space to learn, jam and perform.",
        "logo_url": "/images/clubs/ninaad.JPG",
        "instagram": "@ninaad_bmsce",
        "faculty_name": "Prof. Shankar Mahadevan",
        "faculty_email": "shankar.mahadevan@bmsce.ac.in",
        "member_count": 105,
        "view_count": 235,
        "is_active": True,
        "is_featured": False,
    },
    {
        "name": "The Groovehouse",
        "slug": "groovehouse",
        "category": ClubCategory.EXTRACURRICULAR,
        "subcategory": "music",
        "tagline": "Music & live performance",
        "description": "The music club hosting live performances, competitions and music-based cultural activities.",
        "overview": "The music club hosting live performances, competitions and music-based cultural activities to foster a vibrant musical community.",
        "logo_url": "/images/clubs/GrooveHouse.jpg",
        "instagram": "@groovehouse_bmsce",
        "faculty_name": "Prof. Rahul Dravid",
        "faculty_email": "rahul.dravid@bmsce.ac.in",
        "member_count": 140,
        "view_count": 310,
        "is_active": True,
        "is_featured": False,
    },
    {
        "name": "Panache – Fashion Team",
        "slug": "panache",
        "category": ClubCategory.EXTRACURRICULAR,
        "subcategory": "arts",
        "tagline": "Fashion & styling",
        "description": "The official fashion club hosting fashion shows, styling workshops and competitions.",
        "overview": "The official fashion club of BMSCE hosting fashion shows, styling workshops and competitions for models, designers and makeup artists.",
        "logo_url": "/images/clubs/panache.JPG",
        "instagram": "@panache_bmsce",
        "faculty_name": "Prof. Neha Kapoor",
        "faculty_email": "neha.kapoor@bmsce.ac.in",
        "member_count": 90,
        "view_count": 205,
        "is_active": True,
        "is_featured": False,
    },
    {
        "name": "Paramvah Dance (Eastern)",
        "slug": "paramvah",
        "category": ClubCategory.EXTRACURRICULAR,
        "subcategory": "dance",
        "tagline": "Indian dance & choreography",
        "description": "College dance team specializing in Eastern and Indian contemporary dance forms celebrating cultural heritage.",
        "overview": "College dance team specializing in Eastern and Indian contemporary dance forms, creating expressive performances that celebrate cultural heritage.",
        "logo_url": "/images/clubs/paramvah.JPG",
        "instagram": "@paramvah_bmsce",
        "faculty_name": "Prof. Gayatri Sharma",
        "faculty_email": "gayatri.sharma@bmsce.ac.in",
        "member_count": 85,
        "view_count": 195,
        "is_active": True,
        "is_featured": False,
    },
    {
        "name": "Danz Addix (Western Dance)",
        "slug": "danzaddix",
        "category": ClubCategory.EXTRACURRICULAR,
        "subcategory": "dance",
        "tagline": "Western dance team",
        "description": "The western dance team performing hip-hop and contemporary styles in events and competitions.",
        "overview": "The western dance team performing hip-hop and contemporary styles, participating in events and competitions.",
        "logo_url": "/images/clubs/DanzAddix.jpg",
        "instagram": "@danzaddix_bmsce",
        "faculty_name": "Prof. Rohan Malhotra",
        "faculty_email": "rohan.malhotra@bmsce.ac.in",
        "member_count": 95,
        "view_count": 215,
        "is_active": True,
        "is_featured": False,
    },
    {
        "name": "Fine Arts Club",
        "slug": "finearts",
        "category": ClubCategory.EXTRACURRICULAR,
        "subcategory": "arts",
        "tagline": "Visual arts & painting",
        "description": "A platform for creativity involving drawing, sketching, mehendi, wall painting and artistic expressions.",
        "overview": "A platform for creativity involving drawing, sketching, mehendi, wall painting and other artistic expressions for all skill levels.",
        "logo_url": "/images/clubs/finearts.jpg",
        "instagram": "@finearts_bmsce",
        "faculty_name": "Prof. Kavita Nair",
        "faculty_email": "kavita.nair@bmsce.ac.in",
        "member_count": 115,
        "view_count": 255,
        "is_active": True,
        "is_featured": False,
    },
    {
        "name": "Falcons (Multimedia)",
        "slug": "falcons",
        "category": ClubCategory.EXTRACURRICULAR,
        "subcategory": "arts",
        "tagline": "Photography & multimedia",
        "description": "The multimedia club comprising photographers, videographers, editors and drone operators documenting college events.",
        "overview": "The multimedia club comprising photographers, videographers, editors and drone operators who capture and document major college events.",
        "logo_url": "/images/clubs/Falcons.jpg",
        "instagram": "@falcons_bmsce",
        "faculty_name": "Prof. Arjun Reddy",
        "faculty_email": "arjun.reddy@bmsce.ac.in",
        "member_count": 130,
        "view_count": 290,
        "is_active": True,
        "is_featured": False,
    },
    {
        "name": "Pravrutthi (Theatre)",
        "slug": "pravrutthi",
        "category": ClubCategory.EXTRACURRICULAR,
        "subcategory": "drama",
        "tagline": "Theatre & street performance",
        "description": "The theatre team involved in acting, scriptwriting, stage plays and street performances.",
        "overview": "The theatre team involved in acting, scriptwriting, stage plays and street performances nurturing creativity and expressive storytelling.",
        "logo_url": "/images/clubs/Pravrutthi.JPG",
        "instagram": "@pravrutthi_bmsce",
        "faculty_name": "Prof. Deepak Verma",
        "faculty_email": "deepak.verma@bmsce.ac.in",
        "member_count": 100,
        "view_count": 225,
        "is_active": True,
        "is_featured": False,
    },
    {
        "name": "Chiranthana (Kannada Sangha)",
        "slug": "chiranthana",
        "category": ClubCategory.EXTRACURRICULAR,
        "subcategory": "cultural",
        "tagline": "Kannada language & culture",
        "description": "The Kannada cultural club promoting Kannada language, literature and art with performances and cultural showcases.",
        "overview": "The Kannada cultural club promoting Kannada language, literature and art with performances and cultural showcases.",
        "logo_url": "/images/clubs/chiranthana.jpg",
        "instagram": "@chiranthana_bmsce",
        "faculty_name": "Prof. Sudha Murthy",
        "faculty_email": "sudha.murthy@bmsce.ac.in",
        "member_count": 110,
        "view_count": 245,
        "is_active": True,
        "is_featured": False,
    },
    {
        "name": "Samskruthi Sambhrama",
        "slug": "samskruthi",
        "category": ClubCategory.EXTRACURRICULAR,
        "subcategory": "cultural",
        "tagline": "Folklore & cultural festival",
        "description": "The folklore society celebrating Indian culture and heritage through diverse cultural art forms.",
        "overview": "The folklore society dedicated to celebrating Indian culture and heritage through diverse cultural art forms and performances.",
        "logo_url": "/images/clubs/samskruthi.JPG",
        "instagram": "@samskruthi_bmsce",
        "faculty_name": "Prof. Lakshmi Devi",
        "faculty_email": "lakshmi.devi@bmsce.ac.in",
        "member_count": 120,
        "view_count": 270,
        "is_active": True,
        "is_featured": False,
    },
    {
        "name": "BMS MUNSOC (Model UN)",
        "slug": "munsoc",
        "category": ClubCategory.EXTRACURRICULAR,
        "subcategory": "social",
        "tagline": "Model UN & diplomacy",
        "description": "A platform for developing public policy awareness, diplomacy and oratory skills through Model UN simulations.",
        "overview": "A platform for developing public policy awareness, diplomacy and oratory skills; members discuss, deliberate and resolve global issues.",
        "logo_url": "/images/clubs/munsoc.JPG",
        "instagram": "@munsoc_bmsce",
        "faculty_name": "Prof. Vikram Patel",
        "faculty_email": "vikram.patel@bmsce.ac.in",
        "member_count": 105,
        "view_count": 235,
        "is_active": True,
        "is_featured": False,
    },
]


def seed_clubs(db: Session, clear_existing: bool = False):
    """
    Seed the database with club data

    Args:
        db: Database session
        clear_existing: If True, delete all existing clubs first (WARNING: this will cascade delete memberships and potentially break relationships)
    """
    try:
        if clear_existing:
            print("⚠️  Clearing existing clubs...")
            db.query(Club).delete()
            db.commit()
            print("✅ Existing clubs cleared")

        print(f"\n🌱 Seeding {len(CLUBS_DATA)} clubs...")

        clubs_added = 0
        clubs_skipped = 0

        for club_data in CLUBS_DATA:
            # Check if club already exists (by slug)
            existing_club = db.query(Club).filter(Club.slug == club_data["slug"]).first()

            if existing_club:
                print(f"⏭️  Skipping '{club_data['name']}' - already exists")
                clubs_skipped += 1
                continue

            # Create new club
            club = Club(**club_data)
            db.add(club)
            clubs_added += 1
            print(f"✅ Added: {club_data['name']} ({club_data['category'].value})")

        db.commit()

        print(f"\n📊 Summary:")
        print(f"   ✅ Clubs added: {clubs_added}")
        print(f"   ⏭️  Clubs skipped: {clubs_skipped}")
        print(f"   📝 Total clubs in database: {db.query(Club).count()}")

        # Show statistics by category
        print(f"\n📈 Clubs by category:")
        for category in ClubCategory:
            count = db.query(Club).filter(Club.category == category).count()
            total_members = db.query(Club).filter(Club.category == category).with_entities(
                func.sum(Club.member_count)
            ).scalar() or 0
            print(f"   {category.value.capitalize()}: {count} clubs ({total_members} total members)")

        # Show featured clubs
        featured_count = db.query(Club).filter(Club.is_featured == True).count()
        print(f"\n⭐ Featured clubs: {featured_count}")

        return clubs_added, clubs_skipped

    except Exception as e:
        db.rollback()
        print(f"\n❌ Error seeding clubs: {str(e)}")
        raise


def main():
    """Main function to run the seeding script"""
    print("=" * 60)
    print("ClubCompass - Database Seeding Script")
    print("=" * 60)

    # Check if user wants to clear existing data
    clear_existing = False
    if len(sys.argv) > 1 and sys.argv[1] == "--clear":
        response = input("\n⚠️  WARNING: This will DELETE all existing clubs and related data!\nAre you sure? (yes/no): ")
        if response.lower() == "yes":
            clear_existing = True
        else:
            print("❌ Aborted")
            return

    # Create database session
    db = SessionLocal()

    try:
        # Ensure tables exist
        print("\n🔧 Ensuring database tables exist...")
        Base.metadata.create_all(bind=engine)
        print("✅ Database tables ready")

        # Seed clubs
        seed_clubs(db, clear_existing=clear_existing)

        print("\n✨ Database seeding completed successfully!")
        print("\nYou can now:")
        print("  1. Start the backend: uvicorn app.main:app --reload")
        print("  2. Start the frontend: npm run dev")
        print("  3. Visit http://localhost:3000 to see the clubs")

    except Exception as e:
        print(f"\n💥 Fatal error: {str(e)}")
        import traceback
        traceback.print_exc()
    finally:
        db.close()


if __name__ == "__main__":
    main()
